# Use the official Apache Airflow image as a base image
FROM apache/airflow:2.7.3

# Install additional dependencies
RUN pip install --user pandas polars psycopg2-binary requests SQLAlchemy connectorx pyarrow
